// <auto-generated />
using System;
using FurniturePro.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FurniturePro.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251209154624_Create")]
    partial class Create
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FurniturePro.Core.Entities.Connections.FurnitureComposition", b =>
                {
                    b.Property<int>("Entity1Id")
                        .HasColumnType("integer");

                    b.Property<int>("Entity2Id")
                        .HasColumnType("integer");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamptz");

                    b.HasKey("Entity1Id", "Entity2Id");

                    b.HasIndex("Entity2Id");

                    b.ToTable("furnitureCompositions", (string)null);
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Connections.OrderComposition", b =>
                {
                    b.Property<int>("Entity1Id")
                        .HasColumnType("integer");

                    b.Property<int>("Entity2Id")
                        .HasColumnType("integer");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamptz");

                    b.HasKey("Entity1Id", "Entity2Id");

                    b.HasIndex("Entity2Id");

                    b.ToTable("orderCompositions", (string)null);
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Connections.StatusChange", b =>
                {
                    b.Property<int>("Entity1Id")
                        .HasColumnType("integer");

                    b.Property<int>("Entity2Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamptz");

                    b.HasKey("Entity1Id", "Entity2Id");

                    b.HasIndex("Entity2Id");

                    b.ToTable("statusChanges", (string)null);
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.DeletedId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("TableName", "EntityId")
                        .IsUnique();

                    b.ToTable("deletedIds", (string)null);
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Dictionaries.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Dictionaries.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("FullName")
                        .IsUnique();

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Dictionaries.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("colors", (string)null);
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Dictionaries.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("materials", (string)null);
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Dictionaries.OperationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("operationTypes", (string)null);
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Dictionaries.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("statuses", (string)null);
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Furniture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activity")
                        .HasColumnType("boolean");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("Markup")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("furniture", (string)null);
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Operation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamptz");

                    b.Property<int>("OperationTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("PartId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamptz");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OperationTypeId");

                    b.HasIndex("PartId");

                    b.ToTable("operations", (string)null);
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<int?>("Discount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Part", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activity")
                        .HasColumnType("boolean");

                    b.Property<int?>("ColorId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("Diameter")
                        .HasColumnType("integer");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<int?>("Length")
                        .HasColumnType("integer");

                    b.Property<int?>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamptz");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("parts", (string)null);
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Price", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamptz");

                    b.Property<int>("PartId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamptz");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal");

                    b.HasKey("Id");

                    b.HasIndex("PartId");

                    b.ToTable("prices", (string)null);
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Snapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamptz");

                    b.Property<int>("PartId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamptz");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PartId");

                    b.ToTable("snapshots", (string)null);
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Connections.FurnitureComposition", b =>
                {
                    b.HasOne("FurniturePro.Core.Entities.Furniture", "Entity1")
                        .WithMany("FurnitureCompositions")
                        .HasForeignKey("Entity1Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FurniturePro.Core.Entities.Part", "Entity2")
                        .WithMany()
                        .HasForeignKey("Entity2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity1");

                    b.Navigation("Entity2");
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Connections.OrderComposition", b =>
                {
                    b.HasOne("FurniturePro.Core.Entities.Order", "Entity1")
                        .WithMany("OrderCompositions")
                        .HasForeignKey("Entity1Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FurniturePro.Core.Entities.Furniture", "Entity2")
                        .WithMany("OrderCompositions")
                        .HasForeignKey("Entity2Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Entity1");

                    b.Navigation("Entity2");
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Connections.StatusChange", b =>
                {
                    b.HasOne("FurniturePro.Core.Entities.Order", "Entity1")
                        .WithMany("StatusChanges")
                        .HasForeignKey("Entity1Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FurniturePro.Core.Entities.Dictionaries.Status", "Entity2")
                        .WithMany("StatusChanges")
                        .HasForeignKey("Entity2Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Entity1");

                    b.Navigation("Entity2");
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Furniture", b =>
                {
                    b.HasOne("FurniturePro.Core.Entities.Dictionaries.Category", "Category")
                        .WithMany("Furnitures")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Operation", b =>
                {
                    b.HasOne("FurniturePro.Core.Entities.Dictionaries.OperationType", "OperationType")
                        .WithMany("Operations")
                        .HasForeignKey("OperationTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FurniturePro.Core.Entities.Part", "Part")
                        .WithMany("Operations")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("OperationType");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Order", b =>
                {
                    b.HasOne("FurniturePro.Core.Entities.Dictionaries.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Part", b =>
                {
                    b.HasOne("FurniturePro.Core.Entities.Dictionaries.Color", "Color")
                        .WithMany("Parts")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FurniturePro.Core.Entities.Dictionaries.Material", "Material")
                        .WithMany("Parts")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Color");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Price", b =>
                {
                    b.HasOne("FurniturePro.Core.Entities.Part", "Part")
                        .WithMany("Prices")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Part");
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Snapshot", b =>
                {
                    b.HasOne("FurniturePro.Core.Entities.Part", "Part")
                        .WithMany("Snapshots")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Part");
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Dictionaries.Category", b =>
                {
                    b.Navigation("Furnitures");
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Dictionaries.Client", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Dictionaries.Color", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Dictionaries.Material", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Dictionaries.OperationType", b =>
                {
                    b.Navigation("Operations");
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Dictionaries.Status", b =>
                {
                    b.Navigation("StatusChanges");
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Furniture", b =>
                {
                    b.Navigation("FurnitureCompositions");

                    b.Navigation("OrderCompositions");
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Order", b =>
                {
                    b.Navigation("OrderCompositions");

                    b.Navigation("StatusChanges");
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Part", b =>
                {
                    b.Navigation("Operations");

                    b.Navigation("Prices");

                    b.Navigation("Snapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
