// <auto-generated />
using System;
using FurniturePro.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FurniturePro.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FurniturePro.Core.Entities.Catalog.Furniture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activity")
                        .HasColumnType("boolean");

                    b.Property<int>("BaseDepth")
                        .HasColumnType("integer");

                    b.Property<int>("BaseHeight")
                        .HasColumnType("integer");

                    b.Property<int>("BaseWidth")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("FurnitureCategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("Markup")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FurnitureCategoryId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.HasIndex("UpdateDate");

                    b.ToTable("Furnitures", (string)null);
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Catalog.FurnitureCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UpdateDate");

                    b.ToTable("FurnitureCategories", (string)null);
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Constructor.FurniturePart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FurnitureId")
                        .HasColumnType("integer");

                    b.Property<int>("PartRoleId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("ReplacementGroupId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FurnitureId");

                    b.HasIndex("PartRoleId");

                    b.HasIndex("ReplacementGroupId");

                    b.HasIndex("UpdateDate");

                    b.ToTable("FurnitureParts", (string)null);
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Constructor.PartRole", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("LengthFormula")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WidthFormula")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UpdateDate");

                    b.ToTable("PartRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LengthFormula = "H",
                            Name = "Боковина",
                            UpdateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WidthFormula = "W"
                        },
                        new
                        {
                            Id = 2,
                            LengthFormula = "D",
                            Name = "Крышка",
                            UpdateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WidthFormula = "W"
                        },
                        new
                        {
                            Id = 3,
                            LengthFormula = "D - 2 * T",
                            Name = "Дно",
                            UpdateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WidthFormula = "W"
                        },
                        new
                        {
                            Id = 4,
                            LengthFormula = "D - 2 * T",
                            Name = "Полка",
                            UpdateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WidthFormula = "W - 20"
                        },
                        new
                        {
                            Id = 5,
                            LengthFormula = "H - 4",
                            Name = "Задняя стенка",
                            UpdateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WidthFormula = "W - 4"
                        },
                        new
                        {
                            Id = 6,
                            LengthFormula = "H - 4",
                            Name = "Фасад (Одинарный)",
                            UpdateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WidthFormula = "W - 4"
                        },
                        new
                        {
                            Id = 7,
                            LengthFormula = "H - 4",
                            Name = "Фасад (Двойной распашной)",
                            UpdateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WidthFormula = "W / 2 - 4"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Роль для крепежа и комплектующих. Габариты не высчитываются.",
                            LengthFormula = "0",
                            Name = "Фурнитура",
                            UpdateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WidthFormula = "0"
                        });
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Constructor.ReplacementGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UpdateDate");

                    b.ToTable("ReplacementGroups", (string)null);
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Constructor.ReplacementGroupItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PartId")
                        .HasColumnType("integer");

                    b.Property<int>("ReplacementGroupId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PartId");

                    b.HasIndex("UpdateDate");

                    b.HasIndex("ReplacementGroupId", "PartId")
                        .IsUnique();

                    b.ToTable("ReplacementGroupItems", (string)null);
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Orders.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.HasIndex("UpdateDate");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Orders.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ResponsibleEmployeeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric(18, 2)");

                    b.Property<decimal>("TotalWeight")
                        .HasColumnType("numeric(10, 3)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("ResponsibleEmployeeId");

                    b.HasIndex("UpdateDate");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Orders.OrderComposition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric(18, 2)");

                    b.Property<int?>("Depth")
                        .HasColumnType("integer");

                    b.Property<int>("FurnitureId")
                        .HasColumnType("integer");

                    b.Property<int?>("Length")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric(10, 3)");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FurnitureId");

                    b.HasIndex("OrderId");

                    b.HasIndex("UpdateDate");

                    b.ToTable("OrderCompositions", (string)null);
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Orders.OrderPartDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostPerUnit")
                        .HasColumnType("numeric(18, 2)");

                    b.Property<int>("OrderCompositionId")
                        .HasColumnType("integer");

                    b.Property<int>("PartId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("SawingLength")
                        .HasColumnType("integer");

                    b.Property<int>("SawingWidth")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric(10, 3)");

                    b.HasKey("Id");

                    b.HasIndex("OrderCompositionId");

                    b.HasIndex("PartId");

                    b.HasIndex("UpdateDate");

                    b.ToTable("OrderPartDetails", (string)null);
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Orders.Status", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UpdateDate");

                    b.ToTable("Statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Заказ оформлен, ожидает подтверждения",
                            Name = "Новый",
                            UpdateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Description = "Заказ передан в цех на производство",
                            Name = "В работе",
                            UpdateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Description = "Мебель изготовлена и находится на складе",
                            Name = "Готов",
                            UpdateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Description = "Заказ передан клиенту",
                            Name = "Отгружен",
                            UpdateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Description = "Заказ отменен",
                            Name = "Отменен",
                            UpdateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Orders.StatusChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UpdateDate");

                    b.ToTable("StatusChanges", (string)null);
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Parts.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UpdateDate");

                    b.ToTable("Colors", (string)null);
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Parts.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UpdateDate");

                    b.ToTable("Materials", (string)null);
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Parts.Part", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activity")
                        .HasColumnType("boolean");

                    b.Property<int>("ColorId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PartCategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("PartTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("Thickness")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("WasteCoefficient")
                        .HasColumnType("integer");

                    b.Property<decimal>("WeightPerUnit")
                        .HasColumnType("numeric(10, 3)");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("PartCategoryId");

                    b.HasIndex("PartTypeId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.HasIndex("UpdateDate");

                    b.ToTable("Parts", (string)null);
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Parts.PartCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UpdateDate");

                    b.ToTable("PartCategories", (string)null);
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Parts.PartType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UpdateDate");

                    b.ToTable("PartTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Типичные детали (крепеж, ножки, ручки), не требующие распила и обработки.",
                            Name = "Фурнитура и комплектующие",
                            UpdateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Description = "Листовые и погонажные материалы (ЛДСП, ДВП, МДФ, профили), требующие деталировки.",
                            Name = "Материал для распила",
                            UpdateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Parts.Price", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<int>("PartId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PartId");

                    b.HasIndex("UpdateDate");

                    b.ToTable("Prices", (string)null);
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.System.DeletedId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("ResponsibleEmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ResponsibleEmployeeId");

                    b.HasIndex("UpdateDate");

                    b.HasIndex("TableName", "EntityId");

                    b.ToTable("DeletedIds", (string)null);
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.System.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activity")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SystemRoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("SystemRoleId");

                    b.HasIndex("UpdateDate");

                    b.ToTable("Employees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activity = true,
                            FullName = "Системный Администратор",
                            HashPassword = "$2a$11$4i0QGpkOYfoDT5z2HAvaP.CoZTdHxTTh/9XRjZvu5C3.zhbAtoJ62",
                            Login = "Admin",
                            SystemRoleId = 1,
                            UpdateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.System.SystemRole", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UpdateDate");

                    b.ToTable("SystemRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Полный доступ к системе",
                            Name = "Администратор",
                            UpdateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Description = "Работа с клиентами, заказами и ценами",
                            Name = "Менеджер по продажам",
                            UpdateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Description = "Ведение каталога мебели и спецификаций",
                            Name = "Конструктор",
                            UpdateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Description = "Просмотр заказов, перевод статусов производства",
                            Name = "Мастер цеха",
                            UpdateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Catalog.Furniture", b =>
                {
                    b.HasOne("FurniturePro.Core.Entities.Catalog.FurnitureCategory", "FurnitureCategory")
                        .WithMany("Furnitures")
                        .HasForeignKey("FurnitureCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FurnitureCategory");
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Constructor.FurniturePart", b =>
                {
                    b.HasOne("FurniturePro.Core.Entities.Catalog.Furniture", "Furniture")
                        .WithMany("FurnitureParts")
                        .HasForeignKey("FurnitureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FurniturePro.Core.Entities.Constructor.PartRole", "PartRole")
                        .WithMany("FurnitureParts")
                        .HasForeignKey("PartRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FurniturePro.Core.Entities.Constructor.ReplacementGroup", "ReplacementGroup")
                        .WithMany("FurnitureParts")
                        .HasForeignKey("ReplacementGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Furniture");

                    b.Navigation("PartRole");

                    b.Navigation("ReplacementGroup");
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Constructor.ReplacementGroupItem", b =>
                {
                    b.HasOne("FurniturePro.Core.Entities.Parts.Part", "Part")
                        .WithMany("ReplacementGroupItems")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FurniturePro.Core.Entities.Constructor.ReplacementGroup", "ReplacementGroup")
                        .WithMany("ReplacementGroupItems")
                        .HasForeignKey("ReplacementGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("ReplacementGroup");
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Orders.Order", b =>
                {
                    b.HasOne("FurniturePro.Core.Entities.Orders.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FurniturePro.Core.Entities.System.Employee", "ResponsibleEmployee")
                        .WithMany("ResponsibleForOrders")
                        .HasForeignKey("ResponsibleEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("ResponsibleEmployee");
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Orders.OrderComposition", b =>
                {
                    b.HasOne("FurniturePro.Core.Entities.Catalog.Furniture", "Furniture")
                        .WithMany("OrderCompositions")
                        .HasForeignKey("FurnitureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FurniturePro.Core.Entities.Orders.Order", "Order")
                        .WithMany("OrderCompositions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Furniture");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Orders.OrderPartDetail", b =>
                {
                    b.HasOne("FurniturePro.Core.Entities.Orders.OrderComposition", "OrderComposition")
                        .WithMany("OrderPartDetails")
                        .HasForeignKey("OrderCompositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FurniturePro.Core.Entities.Parts.Part", "Part")
                        .WithMany("OrderPartDetails")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrderComposition");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Orders.StatusChange", b =>
                {
                    b.HasOne("FurniturePro.Core.Entities.Orders.Order", "Order")
                        .WithMany("StatusChanges")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FurniturePro.Core.Entities.Orders.Status", "Status")
                        .WithMany("StatusChanges")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Parts.Part", b =>
                {
                    b.HasOne("FurniturePro.Core.Entities.Parts.Color", "Color")
                        .WithMany("Parts")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FurniturePro.Core.Entities.Parts.Material", "Material")
                        .WithMany("Parts")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FurniturePro.Core.Entities.Parts.PartCategory", "PartCategory")
                        .WithMany("Parts")
                        .HasForeignKey("PartCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FurniturePro.Core.Entities.Parts.PartType", "PartType")
                        .WithMany("Parts")
                        .HasForeignKey("PartTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("Material");

                    b.Navigation("PartCategory");

                    b.Navigation("PartType");
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Parts.Price", b =>
                {
                    b.HasOne("FurniturePro.Core.Entities.System.Employee", "Employee")
                        .WithMany("SetPrices")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FurniturePro.Core.Entities.Parts.Part", "Part")
                        .WithMany("Prices")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.System.DeletedId", b =>
                {
                    b.HasOne("FurniturePro.Core.Entities.System.Employee", "ResponsibleEmployee")
                        .WithMany()
                        .HasForeignKey("ResponsibleEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ResponsibleEmployee");
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.System.Employee", b =>
                {
                    b.HasOne("FurniturePro.Core.Entities.System.SystemRole", "SystemRole")
                        .WithMany("Employees")
                        .HasForeignKey("SystemRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SystemRole");
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Catalog.Furniture", b =>
                {
                    b.Navigation("FurnitureParts");

                    b.Navigation("OrderCompositions");
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Catalog.FurnitureCategory", b =>
                {
                    b.Navigation("Furnitures");
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Constructor.PartRole", b =>
                {
                    b.Navigation("FurnitureParts");
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Constructor.ReplacementGroup", b =>
                {
                    b.Navigation("FurnitureParts");

                    b.Navigation("ReplacementGroupItems");
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Orders.Client", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Orders.Order", b =>
                {
                    b.Navigation("OrderCompositions");

                    b.Navigation("StatusChanges");
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Orders.OrderComposition", b =>
                {
                    b.Navigation("OrderPartDetails");
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Orders.Status", b =>
                {
                    b.Navigation("StatusChanges");
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Parts.Color", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Parts.Material", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Parts.Part", b =>
                {
                    b.Navigation("OrderPartDetails");

                    b.Navigation("Prices");

                    b.Navigation("ReplacementGroupItems");
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Parts.PartCategory", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.Parts.PartType", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.System.Employee", b =>
                {
                    b.Navigation("ResponsibleForOrders");

                    b.Navigation("SetPrices");
                });

            modelBuilder.Entity("FurniturePro.Core.Entities.System.SystemRole", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
